# fly.toml app configuration file generated for 7-gamble-central on 2024-06-10T17:49:09+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '7-gamble-central'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
